## Dynamic configuration
http:
  routers:
    to-webserver:
      service: webserver
      rule: "PathPrefix(`/auth`)"

    to-auth:
      service: auth
      middlewares:
        - "auth-api-strip"
      rule: "Path(`/auth/api/{case:[a-z]+}`)"

  middlewares:
    auth-api-strip:
      stripPrefix:
        prefixes:
          - "/auth/api"

    forward-auth:
      forwardAuth:
        address: "http://host.docker.internal:8000/verify"
        trustForwardHeader: true

  services:
    webserver:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"
    auth:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8000"
