# syntax=docker/dockerfile:1.2
FROM node:14 as builder

# Build the frontend application
WORKDIR /frontend
COPY frontend/package.json .
COPY frontend/src ./src
COPY frontend/public ./public
RUN npm install
RUN npm run build

# EXTERNAL STAGE
FROM nginx:stable-alpine

COPY --from=builder /frontend/build /usr/share/nginx/html/auth
#COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
