version: '3'

services:
  traefik:
    image: traefik:v2.7
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock




  database:
    image: "postgres:14.0-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users

  crowsnest-auth-frontend:
    build: 
      context: ./
      dockerfile: Dockerfile-frontend
    labels:
      - traefik.http.routers.crowsnest-auth-frontend.rule=PathPrefix(`/auth`)
      - traefik.http.services.crowsnest-auth-frontend.loadbalancer.server.port=80

  crowsnest-auth:
    restart: unless-stopped
    depends_on:
      - database
    build: 
      context: ./
      dockerfile: Dockerfile-backend
    labels:
      - traefik.http.routers.crowsnest-auth.rule=Path(`/auth/api/{case:[\/_a-z]+}`)
      - traefik.http.middlewares.auth-strip.stripprefix.prefixes=/auth/api
      - traefik.http.routers.crowsnest-auth.middlewares=auth-strip
      - traefik.http.middlewares.crowsnest-auth.forwardauth.address=http://crowsnest-auth/verify
      - traefik.http.middlewares.crowsnest-auth.forwardauth.trustForwardHeader=true
      - traefik.http.services.crowsnest-auth.loadbalancer.server.port=80
    environment:
      - USER_DATABASE_URL=postgresql://admin:password@database/users
      - ACCESS_COOKIE_DOMAIN=localhost 
      - ACCESS_COOKIE_HTTPONLY=true
      - ACCESS_TOKEN_EXPIRE_MINUTES=5
      - ADMIN_USER_PASSWORD=password
      - BASE_URL=/auth/api

  admin:
    image: containous/whoami:latest
    labels:
      - traefik.http.routers.admin.rule=Path(`/admin`)
      - traefik.http.routers.admin.middlewares=crowsnest-auth

  white:
    image: containous/whoami:latest
    labels:
      - traefik.http.routers.white.rule=Path(`/white`)
      - traefik.http.routers.white.middlewares=crowsnest-auth
    depends_on:
      - crowsnest-auth
    

  black:
    image: containous/whoami:latest
    labels:
      - traefik.http.routers.black.rule=Path(`/black`)
      - traefik.http.routers.black.middlewares=crowsnest-auth
    depends_on:
      - crowsnest-auth

  emqx:
    image: emqx/emqx:4.4.4
    labels:
      - "traefik.http.routers.emqx-ws.rule=PathPrefix(`/mqtt`)"
      - "traefik.http.routers.emqx-ws.service=emqx-ws"
      - "traefik.http.services.emqx-ws.loadbalancer.server.port=8083"
    ports:
      - "18083:18083"    
    environment:
      - EMQX_NAME=test-emqx
      - EMQX_LOG__LEVEL=debug
      - EMQX_LOG__TO=console
      #- EMQX_LOADED_PLUGINS="emqx_auth_http"
      #- EMQX_AUTH__HTTP__AUTH_REQ__URL=http://crowsnest-auth/login
      #- EMQX_AUTH__HTTP__AUTH_REQ__METHOD=post
      #- EMQX_AUTH__HTTP__AUTH_REQ__HEADERS__CONTENT-TYPE=application/x-www-form-urlencoded
      #- EMQX_AUTH__HTTP__AUTH_REQ__PARAMS=username=%u,password=%P