version: '3'
services:

  traefik:
    image: "traefik:v2.4"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.file.filename=/dev-service-config.yml"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--entrypoints.mqtt.address=:1883"
    ports:
      - 80:80
      - 443:443
      - 1883:1883
      - 8080:8080

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./dev-service-config.yml:/dev-service-config.yml"

  http_microservice:
    image: containous/whoami:latest
    
    labels:
      - traefik.http.routers.http_example.rule=Path(`/whoami`)
      - traefik.http.routers.http_example.middlewares=forward-auth@file
  
  database:
     image: "postgres:14.0-alpine"
     ports:
      - 5432:5432
     environment:
       - POSTGRES_USER=admin
       - POSTGRES_PASSWORD=password
       - POSTGRES_DB=users
 
#  emqx:
#    image: emqx/emqx
#    ports:
#      - 8083:8083
#      - 8001:18083
#    environment:
#      - EMQX_NAME=test
#      - EMQX_LOADED_PLUGINS="emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_http"
#      - EMQX_AUTH__HTTP__AUTH_REQ__URL=http://crowsnest-auth/login
#      - EMQX_AUTH__HTTP__AUTH_REQ__METHOD=post
#      - EMQX_AUTH__HTTP__AUTH_REQ__HEADERS__CONTENT-TYPE=application/x-www-form-urlencoded
#      - EMQX_AUTH__HTTP__AUTH_REQ__PARAMS=username=%u,password=%P
#      - EMQX_AUTH__HTTP__ACL_REQ__URL=http://crowsnest-auth/verify_emqx
#      - EMQX_AUTH__HTTP__ACL_REQ__METHOD=get
#      - EMQX_AUTH__HTTP__ACL_REQ__PARAMS=username=%u,topic=%t


    